name: lint (pre-commit)

on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "LICENSE"  
  push:
    paths-ignore:
      - "**/*.md"
      - "LICENSE"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
      with:
        go-version: v1.20.x
    - name: Install dependencies
      run: |
        cd /tmp && go install github.com/go-critic/go-critic/cmd/gocritic@latest
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
        go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
        go install golang.org/x/lint/golint@latest
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
    - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      with: 
        extra_args: --all-files
